std_msgs/Header header
geometry_msgs/Quaternion quaternion # From Inertial frame to Body frame
geometry_msgs/Vector3 rpy_rad # [rad]
geometry_msgs/Vector3 rpy_deg # [deg]
float64 heading_alt # [deg]
float64 heading_LORD # [deg]
geometry_msgs/Vector3 linear_accel # [m/s^2]
geometry_msgs/Vector3 ang_vel_rad # [rad/s]
geometry_msgs/Vector3 ang_vel_deg # [deg/s]
geometry_msgs/Vector3 ang_accel_rad # [rad/s]
geometry_msgs/Vector3 ang_accel_deg # [deg/s]